server:
  port: 8888
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

spring:
  application:
    name: config-service
  profiles:
    active: default
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
  cloud:
    config:
      server:
        native:
          search-locations: ${NATIVE_LOCATION}
        git:
          uri: https://github.com/kakao-tech-bootcamp-team-2/config-repo
          search-paths:
          - '{application}'
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true

management:
  endpoints:
    web:
      exposure:
        include: health, bus-refresh
