spring:
  profiles:
    active: native
  rabbitmq:
    host: ${vault.rabbitmq_host}
    port: ${vault.rabbitmq_port}
    username: ${vault.rabbitmq_username}
    password: ${vault.rabbitmq_password}
  cloud:
    config:
      server:
        native:
          search-locations: ${vault.native_location}
        git:
          uri: https://github.com/kakao-tech-bootcamp-team-2/config-repo
          search-paths:
          - '{application}'
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true

management:
  endpoints:
    web:
      exposure:
        include: health, bus-refresh
